### ISSUE TITLE
mdnext-twin-macro 🚀

### ISSUE THREAD

**Issue by will-t-harris** [domitriusclark/mdnext#45]
This issue is to track developing a `mdnext` template that is configured to use `twin.macro` with `emotion` by default.

## The Plan

- Install `twin.macro` with the required `emotion` dependencies.
- Enable babel macros and the `css` prop in `.babelrc`
- Add twin's recommended config as a `babelMacros` field in `package.json`
- Add the `tailwind.config.js` file to project root, not sure if we want to add some config options here to demonstrate how the file works. 🤔
- Add some basic styles to `pages/index.js` to show how the syntax for the `tw` and `css` props work.
- Wrap the app with twin's `GlobalStyles` component to apply tailwind's [preflight base styles](https://unpkg.com/tailwindcss/dist/base.css) to smooth over browser inconsistencies. This will live in `_app.js`
- The `Component` prop in `_app.js` returns a fragment, so we need to wrap this in an element if we want to attach global layout styles. My thinking is that a `main` element would work well for this, but I'm not 100% sure. Definitely open to other approaches for adding global styles if we can think of any.

---

Anything else you think I should add to this @domitriusclark?

**Comment by domitriusclark** [comment]
I've yet to dig into Tailwind, let alone `twin.macro`, so I'm really excited to see this. 

My rule of thumb for starters is to think of what makes you feel most productive with the setup. Once you're there we could think if there'd be any other nice-to-have's to round it out.

I think seeing more templates will help me get into the decision making behind what a template should be.
Mixed bag of opinions? 
Should it have an end goal in mind (ie Blog, Ecomm, etc)?
...things like that. 

Happy to hear what you think 👂

**Comment by will-t-harris** [comment]
I guess I was thinking that this would be a way for people to install `mdnext` with `twin.macro`/`emotion` configured and ready to use out of the box.

I could definitely see the argument that a template should be targeted toward a specific use-case (like you're saying: blog, ecom, marketing page, etc). 

I could also see it being useful to have less opinionated templates that get people to the starting line with specific tooling set up and ready to go.

I was thinking that the `twin` template would be closer to the latter. As a tool, I don't think `twin` lends itself to any specific use-case over any other. 

Do you think that there is room for both types of templates, or were you aiming more toward templates having direct end goals in mind?

**Comment by domitriusclark** [comment]
No I definitely do, I've been more teetering between the two and hoping to leverage some feedback from those wanted to submit templates 👍

**Comment by mwarger** [comment]
@will-t-harris  @domitriusclark I'm having an issue with this plugin.  

```
Error: A PostCSS Plugin was passed as a function using require(), but it must be provided as a string.
Read more: https://err.sh/next.js/postcss-shape
Error: Malformed PostCSS Configuration
```

I've tried upgrading all the packages as well, and receive the same error.  Any thoughts on what could be done about this?

**Comment by will-t-harris** [comment]
Hey @mwarger, sorry you're having an issue with the template. Any chance you could provide a reproduction in a codesandbox for what's going on in your situation? When I run the template locally I get no errors.

Thanks! :+1:

**Comment by mwarger** [comment]
I run the command to use the template and run `yarn install`

<img width="542" alt="Screen Shot 2020-12-15 at 10 34 35 AM" src="https://user-images.githubusercontent.com/686823/102244117-87a0ba80-3ec1-11eb-8cbe-1cc76743cd46.png">

I run `yarn dev` to run the app and get this error:
<img width="801" alt="Screen Shot 2020-12-15 at 10 34 44 AM" src="https://user-images.githubusercontent.com/686823/102244222-a3a45c00-3ec1-11eb-9c80-a4a2b6662f63.png">

Repro repo here: https://github.com/mwarger/twin-blog-repro

**Comment by will-t-harris** [comment]
One thing I'm noticing is that your repro is using packages that are not even with [the current template](https://github.com/domitriusclark/mdnext/blob/master/templates/mdnext-twin-macro/package.json). I am still able to run your reproduction locally, however, which makes me think that this is not the root issue.

@domitriusclark it seems like my most recent twin PR isn't what's being served by the `npx mdnext` command, any idea why that might be happening?

**Comment by will-t-harris** [comment]
@mwarger can you try cloning and running [this repo](https://github.com/will-t-harris/mdnext-twin-macro)?

**Comment by mwarger** [comment]
> @mwarger can you try cloning and running [this repo](https://github.com/will-t-harris/mdnext-twin-macro)?

@will-t-harris What do you mean by "running" it?

**Comment by will-t-harris** [comment]
> > @mwarger can you try cloning and running [this repo](https://github.com/will-t-harris/mdnext-twin-macro)?
> 
> @will-t-harris What do you mean by "running" it?

- Clone the repo to your computer
- cd into the directory you cloned it into
- run yarn to install packages
- run yarn dev to run the project locally

**Comment by mwarger** [comment]
@will-t-harris There is no `dev` script.  Are you referring to a different package or branch?  Did you send the wrong link?

**Comment by will-t-harris** [comment]
Try switching to the `mdnext-twin-macro` branch in the link that I sent, then cd into `mdnext-twin-macro/templates/mdnext-twin-macro` and run `yarn` then `yarn dev`.

This is the local branch that I've been developing the template off of, hopefully that will compile for you.

**Comment by mwarger** [comment]
@will-t-harris After doing that I see this:

![image](https://user-images.githubusercontent.com/686823/102275641-55a44e00-3eeb-11eb-929d-556bc9825224.png)

**Comment by will-t-harris** [comment]
@mwarger unfortunately I'm not sure what else to suggest, as I'm unable to reproduce your issue locally.

It might be worth going through the twin/next [installation docs](https://github.com/ben-rogerson/twin.examples/tree/master/next-emotion#installation) and making sure everything you have locally lines up.

**Comment by mwarger** [comment]
@will-t-harris Do you maybe have something globally installed that would let this work for you?  Have you used the template from a fresh checkout?  Do you have a repo that has your working set up so we can see if there are any differences between our setups?  Thanks.

**Comment by will-t-harris** [comment]
1. Not a global install issue, I just tried cloning the project down on a different computer that has very little installed and was able to compile. This covers your question about a fresh checkout as well.
2. I'm sure the main difference is going to be that I develop on linux (mint, based on ubuntu), but I'd be surprised to learn that there was a breaking difference between linux and macos. I don't have a public repo with my working setup

**Comment by mwarger** [comment]
@will-t-harris I'm sorry, this was (by now, obviously) totally my fault.  At some point recently I had gotten a postcss config file generated in that `scratch` folder that was in my path above.  This was being found by the project in the ancestral file tree.  I noticed this after starting a different boilerplate and seeing the same error.  Thanks for your time with this - it works great now!

**Comment by will-t-harris** [comment]
@mwarger no worries, I'm glad you got it sorted :rocket:
