### ISSUE TITLE
Demo of Templates

### ISSUE THREAD

**Issue by jsjoeio** [domitriusclark/mdnext#65]
Hey Dom! 👋🏼

Thanks a ton for making `mdnext` and to the community for the templates!

I'm having trouble deciding between templates. I would love if the were each deployed so you could see live demos before choosing. Not sure if that's on the roadmap but thought I'd throw it out there!

**Comment by domitriusclark** [comment]
@jsjoeio ! Super stoked your digging it.

Been thinking about attaching a Codesandbox for each. Would that be helpful?

**Comment by jsjoeio** [comment]
@domitriusclark 100%! That would be great 🙏🏼

**Comment by domitriusclark** [comment]
finally getting around to this! just added two new sandboxes
